language: php

sudo: required

before_install:
  - composer self-update --rollback
  - sudo apt-get update
  - sudo apt-get install ffmpeg
  - phpenv config-rm xdebug.ini
install:
  - composer update --prefer-source

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
