language: php

#sudo: required

before_install:
  - add-apt-repository ppa:mc3man/trusty-media -y
  - apt-get update
  - apt-get install ffmpeg
  - phpenv config-rm xdebug.ini
install:
  - composer update --prefer-source

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true
